module.exports = {
	debts: require('./debts'),
	fees: require('./fees'),
	checkoutCosts: require('./checkoutCosts'),
	rooms: require('./rooms'),
	buildings: require('./buildings'),
	receipts: require('./receipts'),
	invoices: require('./invoices'),
	customers: require('./customers'),
	revenues: require('./revenues'),
	expenditures: require('./expenditures'),
	statistics: require('./statistics'),
	deposits: require('./deposits'),
	depositRefunds: require('./depositRefunds'),
	notifications: require('./notifications'),
	users: require('./users'),
	transactions: require('./transactions'),
	tasks: require('./tasks'),
	vehicles: require('./vehicles'),
};
