const IDEMPOTENCY_RECORD_STATUS = {
	PROCESSING: 'PROCESSING',
	SUCCESS: 'SUCCESS',
	FAILED_RETRYABLE: 'FAILED_RETRYABLE',
	FAILED_FINAL: 'FAILED_FINAL',
};

module.exports = {
	IDEMPOTENCY_RECORD_STATUS,
};
