const roles = require('./userRoles');

//PERMISSION DEFINITION
const PERMISSIONS = {
	// ====== BUILDING ===== //
	EDIT_BUILDING_INFO: 'EDIT_BUILDING_INFO',
	VIEW_BUILDING_CONTRACT: 'VIEW_BUILDING_CONTRACT',
	EDIT_BUILDING_CONTRACT: 'EDIT_BUILDING_CONTRACT',

	VIEW_BUILDING_DEPOSIT_TERM: 'VIEW_BUILDING_DEPOSIT_TERM',
	EDIT_BUILDING_DEPOSIT_TERM: 'EDIT_BUILDING_DEPOSIT_TERM',

	// ====== ROOM ===== //
	VIEW_ROOMS: 'VIEW_ROOMS',
	VIEW_ROOM_DETAIL: 'VIEW_ROOM_DETAIL',
	EDIT_ROOM_INFO: 'EDIT_ROOM_INFO',
	VIEW_ROOM_HISTORY: 'VIEW_ROOM_HISTORY',

	// ====== FEES ===== //
	EDIT_FEE: 'EDIT_FEE',
	DELETE_FEE: 'DELETE_FEE',

	// ====== BILLS ===== //
	VIEW_BILLS: 'VIEW_BILLS',
	EDIT_BILL: 'EDIT_BILL',
	DELETE_BILL: 'DELETE_BILL',
	ADD_BILL: 'ADD_BILL',

	// ====== TRANSACTIONS ===== //
	COLLECT_CASH: 'COLLECT_CASH',
	PAYMENT_REQUEST: 'PAYMENT_REQUEST',

	// ====== REPORTS ===== //
	VIEW_STATISTICS: 'VIEW_STATISTICS',
	VIEW_INCOME_EXPENDITURE: 'VIEW_INCOME_EXPENDITURE',

	ADD_INCIDENTAL_INCOME: 'ADD_INCIDENTAL_INCOME',
	DELETE_INCIDENTAL_INCOME: 'DELETE_INCIDENTAL_INCOME',
	EDIT_INCIDENTAL_INCOME: 'EDIT_INCIDENTAL_INCOME',

	ADD_EXPENDITURE: 'ADD_EXPENDITURE',
	EDIT_EXPENDITURE: 'EDIT_EXPENDITURE',
	DELETE_EXPENDITURE: 'DELETE_EXPENDITURE',

	FINANCE_SETTLEMENT: 'FINANCE_SETTLEMENT', // ONLY FOR OWNER !

	// ====== DEPOSITS ===== //
	VIEW_DEPOSITS: 'VIEW_DEPOSITS',
	EDIT_DEPOSIT: 'EDIT_DEPOSIT',
	DELETE_DEPOSIT: 'DELETE_DEPOSIT',
	ADD_DEPOSIT: 'ADD_DEPOSIT',

	VIEW_DEPOSIT_REFUND: 'VIEW_DEPOSIT_REFUND',
	EDIT_DEPOSIT_REFUND: 'EDIT_DEPOSIT_REFUND',
	DELETE_DEPOSIT_REFUND: 'DELETE_DEPOSIT_REFUND',
	ADD_DEPOSIT_REFUND: 'ADD_DEPOSIT_REFUND',

	// ====== CONTRACT ===== //
	VIEW_CONTRACT: 'VIEW_CONTRACT',
	EDIT_CONTRACT: 'EDIT_CONTRACT',

	// ====== CHECKOUT COST ===== //
	// VIEW_CHECKOUT_COST: 'VIEW_CHECKOUT_COST',
	// EDIT_CHECKOUT_COST: 'EDIT_CHECKOUT_COST',
	// DELETE_CHECKOUT_COST: 'DELETE_CHECKOUT_COST',

	VIEW_CHECKOUT_EARLY: 'VIEW_CHECKOUT_EARLY',
	EDIT_CHECKOUT_EARLY: 'EDIT_CHECKOUT_EARLY',
	DELETE_CHECKOUT_EARLY: 'DELETE_CHECKOUT_EARLY',
	ADD_CHECKOUT_EARLY: 'ADD_CHECKOUT_EARLY',

	// ====== CUSTOMERS ===== //
	VIEW_CUSTOMERS: 'VIEW_CUSTOMERS',
	EDIT_CUSTOMER: 'EDIT_CUSTOMER',
	DELETE_CUSTOMER: 'DELETE_CUSTOMER',
	ADD_CUSTOMER: 'ADD_CUSTOMER',

	// ====== VEHICLES ===== //
	VIEW_VEHICLES: 'VIEW_VEHICLES',
	EDIT_VEHICLE: 'EDIT_VEHICLE',
	DELETE_VEHICLE: 'DELETE_VEHICLE',
	ADD_VEHICLE: 'ADD_VEHICLE',

	//====== TASKS ===== //
	VIEW_TASKS: 'VIEW_TASKS',
	EDIT_TASKS: 'EDIT_TASKS',
	DELETE_TASKS: 'DELETE_TASKS',

	//====== DEBTS ====== //
	VIEW_DEBTS: 'VIEW_DEBTS',
	EDIT_DEBTS: 'EDIT_DEBTS',
	DELETE_DEBTS: 'DELETE_DEBTS',

	//===== BANKS ===== //
	VIEW_BANKS: 'VIEW_BANKS',
	// EDIT_BANKS: 'EDIT_BANKS', // ADMIN ONLY
	// DELETE_BANKS: 'DELETE_BANKS', // ADMIN ONLY

	//===== SYSTEM ===== //
	SEND_NOTIFICATION: 'SEND_NOTIFICATION',

	VIEW_MANAGEMENTS: 'VIEW_MANAGEMENTS',
	ADD_MANAGEMENT: 'ADD_MANAGEMENT',
	EDIT_MANAGEMENT: 'EDIT_MANAGEMENT',
	DELETE_MANAGEMENT: 'DELETE_MANAGEMENT',

	VIEW_USER_INFO: 'VIEW_USER_INFO',
	EDIT_USER_INFO: 'EDIT_USER_INFO',

	VIEW_COMPANY_PERMISSIONS: 'VIEW_COMPANY_PERMISSIONS',
	EDIT_COMPANY_PERMISSIONS: 'EDIT_COMPANY_PERMISSIONS',
};

const ROLE_PERMISSIONS = {
	[roles['OWNER']]: ['*'],
	[roles['MANAGER']]: [
		PERMISSIONS['VIEW_ROOMS'],
		PERMISSIONS['VIEW_BUILDING_CONTRACT'],
		PERMISSIONS['VIEW_BUILDING_DEPOSIT_TERM'],
		PERMISSIONS['VIEW_ROOM_DETAIL'],
		PERMISSIONS['EDIT_ROOM_INFO'],
		PERMISSIONS['VIEW_ROOM_HISTORY'],
		PERMISSIONS['EDIT_FEE'],
		PERMISSIONS['DELETE_FEE'],
		PERMISSIONS['VIEW_BILLS'],
		PERMISSIONS['EDIT_BILL'],
		PERMISSIONS['ADD_BILL'],
		PERMISSIONS['DELETE_BILL'],
		PERMISSIONS['COLLECT_CASH'],
		PERMISSIONS['PAYMENT_REQUEST'],
		PERMISSIONS['VIEW_STATISTICS'],
		PERMISSIONS['VIEW_INCOME_EXPENDITURE'],
		PERMISSIONS['ADD_EXPENDITURE'],
		PERMISSIONS['EDIT_EXPENDITURE'],
		PERMISSIONS['DELETE_EXPENDITURE'],
		PERMISSIONS['ADD_INCIDENTAL_INCOME'],
		PERMISSIONS['DELETE_INCIDENTAL_INCOME'],
		PERMISSIONS['EDIT_INCIDENTAL_INCOME'],
		PERMISSIONS['VIEW_DEPOSITS'],
		PERMISSIONS['EDIT_DEPOSIT'],
		PERMISSIONS['DELETE_DEPOSIT'],
		PERMISSIONS['ADD_DEPOSIT'],
		PERMISSIONS['VIEW_DEPOSIT_REFUND'],
		PERMISSIONS['EDIT_DEPOSIT_REFUND'],
		PERMISSIONS['DELETE_DEPOSIT_REFUND'],
		PERMISSIONS['ADD_DEPOSIT_REFUND'],
		PERMISSIONS['VIEW_CHECKOUT_EARLY'],
		PERMISSIONS['EDIT_CHECKOUT_EARLY'],
		PERMISSIONS['DELETE_CHECKOUT_EARLY'],
		PERMISSIONS['ADD_CHECKOUT_EARLY'],
		PERMISSIONS['VIEW_CUSTOMERS'],
		PERMISSIONS['EDIT_CUSTOMER'],
		PERMISSIONS['DELETE_CUSTOMER'],
		PERMISSIONS['ADD_CUSTOMER'],
		PERMISSIONS['VIEW_VEHICLES'],
		PERMISSIONS['EDIT_VEHICLE'],
		PERMISSIONS['DELETE_VEHICLE'],
		PERMISSIONS['ADD_VEHICLE'],
		PERMISSIONS['VIEW_TASKS'],
		PERMISSIONS['EDIT_TASKS'],
		PERMISSIONS['DELETE_TASKS'],
		PERMISSIONS['VIEW_DEBTS'],
		PERMISSIONS['EDIT_DEBTS'],
		PERMISSIONS['DELETE_DEBTS'],

		PERMISSIONS['VIEW_USER_INFO'],
		PERMISSIONS['EDIT_USER_INFO'],
	],

	[roles['STAFF']]: [
		PERMISSIONS['VIEW_BUILDING_CONTRACT'],

		PERMISSIONS['VIEW_BUILDING_DEPOSIT_TERM'],

		PERMISSIONS['VIEW_ROOMS'],

		PERMISSIONS['VIEW_BILLS'],

		PERMISSIONS['VIEW_DEPOSITS'],

		PERMISSIONS['VIEW_DEPOSIT_REFUND'],

		PERMISSIONS['VIEW_CHECKOUT_EARLY'],

		PERMISSIONS['VIEW_CUSTOMERS'],

		PERMISSIONS['VIEW_VEHICLES'],

		PERMISSIONS['VIEW_TASKS'],

		PERMISSIONS['EDIT_TASKS'],

		PERMISSIONS['VIEW_DEBTS'],

		PERMISSIONS['VIEW_USER_INFO'],
	],
};

module.exports = {
	PERMISSIONS,
	ROLE_PERMISSIONS,
};
